[package]
name = "wasmer-runtime-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
chrono = "0.4.24"

[profile.release]
lto = true
